name: remindcare_app
description: RemindCare - Reminder Jadwal Minum Obat

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.1
  web_socket_channel: ^3.0.1
  web_socket_channel: ^3.0.1
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
